/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "RingBuffer.h"
#include "gpio_driver.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

alignas(DataStructure::RingBuffer<uint16>) uint8 ringBufferObjMemory[sizeof(DataStructure::RingBuffer<uint16>)];
uint16 ringBuffer[5];
DataStructure::RingBuffer<uint16>* rb = nullptr;


int main()
{
    /* Loop forever */

	for(;;);
}
