/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "RingBuffer.h"
#include "gpio_driver.h"
#include "usart_driver.h"
#include "tim_driver.h"
#include "HCSR04.h"

extern "C" void initialise_monitor_handles(void);

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


uint8_t txData = 1;
uint8_t startOfData = 0xDE;
uint8_t endOfData = 0xAD;
float distance;
Driver::GP_TIM timer2(TIM2, 16, 0xFFFFFFFFu);

extern "C" void TIM2_IRQHandler(void)
{
	timer2.input_capture_mode_irq_handling();
}

static void PLL_Enable(uint32 pllInputMultyply)
{
	/* Enable HSI oscillator */
	RCC->CR |= RCC_CR_HSION;

	/* Wait for HSI oscillator to stabilize */
	while(!(RCC->CR & RCC_CR_HSIRDY));

	/* Configure PLL */
	RCC->CFGR &= ~(RCC_CFGR_PLLSRC | RCC_CFGR_PLLMUL);
	RCC->CFGR |= RCC_CFGR_PLLSRC_HSI_Div2 | pllInputMultyply;

	/* Enable PLL */
	RCC->CR |= RCC_CR_PLLON;

	/* Wait for PLL to lock */
	while(!(RCC->CR & RCC_CR_PLLRDY));

	/* Switch system clock to PLL */
	RCC->CFGR &= ~RCC_CFGR_SW;
	RCC->CFGR |= RCC_CFGR_SW_PLL;

	/* Wait for system clock switch */
	while((RCC->CFGR & RCC_CFGR_SWS) != RCC_CFGR_SWS_PLL);
}


int main()
{
	initialise_monitor_handles();

	PLL_Enable(RCC_CFGR_PLLMUL4);

	Driver::TIM timer6(TIM6, 16);
	timer6.init();

	/* USART2_TX */
	Driver::GPIO gpioa2(GPIOA, Driver::GPIO::GpioPin::P2, Driver::GPIO::Mode::AlternateFunctionMode,
			Driver::GPIO::Speed::HighSpeed, Driver::GPIO::PullUpDown::NoPull, Driver::GPIO::OutputType::PushPull
			, Driver::GPIO::AlternateFunctionality::AF1);
	/* USART2_RX */
	Driver::GPIO gpioa3(GPIOA, Driver::GPIO::GpioPin::P3, Driver::GPIO::Mode::AlternateFunctionMode,
				Driver::GPIO::Speed::HighSpeed, Driver::GPIO::PullUpDown::NoPull, Driver::GPIO::OutputType::PushPull
				, Driver::GPIO::AlternateFunctionality::AF1);

	/* TIM2_CH1_ETR */
	Driver::GPIO gpioa0(GPIOA, Driver::GPIO::GpioPin::P0, Driver::GPIO::Mode::AlternateFunctionMode,
				Driver::GPIO::Speed::HighSpeed, Driver::GPIO::PullUpDown::NoPull, Driver::GPIO::OutputType::PushPull
				, Driver::GPIO::AlternateFunctionality::AF2);

	/* Sensor Trigger */
	Driver::GPIO gpioc8(GPIOC, Driver::GPIO::GpioPin::P8, Driver::GPIO::Mode::OutputMode,
				Driver::GPIO::Speed::MediumSpeed, Driver::GPIO::PullUpDown::PullDown, Driver::GPIO::OutputType::PushPull);

	Driver::USART usart2(USART2, 16000000, 115200);

	timer2.init();
	timer2.input_capture_mode_config();

    /* Loop forever */
	Driver::GpioHelper::bit_set_reset_config(GPIOC, Driver::GPIO::GpioPin::P8, SET);
	//Sensor::HCSR04 hcsr04("HCSR04");
	while(1)
	{
#if(0)
		int i;
		usart2.write_byte(startOfData);
	    for(i = 0; i < 13; i++)
	    {
	    	usart2.write_byte(txData);
	    	txData++;
	    	timer6.delay_ms(100);
	    }
	    usart2.write_byte(endOfData);
#endif
		/* Testing input capture mode for TIM2 where GPIOC PIN 8 is connected to GPIOA PIN 0 (timer 2 input capture AF set) */
	    Driver::GpioHelper::toggle_pin(GPIOC, Driver::GPIO::GpioPin::P8);
	    timer6.delay_us(40);
	    Driver::GpioHelper::toggle_pin(GPIOC, Driver::GPIO::GpioPin::P8);
	    timer6.delay_ms(200);
	    //distance = hcsr04.to_distance(timer2.get_capture_value(), Sensor::HCSR04::Unit::centimeters);

	}
}
